default_language_version:
    python: python3.9

repos:
    - repo: local
      hooks:
          - id: flake8
            name: flake8
            entry: poetry run flake8
            language: system
            types: [python]
            # files: scraper/scraping_data.py
          - id: mypy
            name: mypy
            entry: poetry run mypy
            language: system
            types: [python]
            # files: scraper.*
          - id: isort
            name: isort
            entry: poetry run isort
            language: system
            types: [python]
            # files: scraper.*

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: double-quote-string-fixer
          - id: check-case-conflict
          - id: mixed-line-ending
          - id: check-ast
          - id: debug-statements
