name: push_image_to_gcp_artifact_registry

on:
    push:
        branches: [master, main, dev]
    pull_request:
        branches: [master, main, dev]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:

        -
            name: code checkout
            uses: actions/checkout@v2

        -
            name: install the gcloud cli
            uses: google-github-actions/setup-gcloud@v0
            with:
                project_id: ${{ secrets.GOOGLE_PROJECT }}
                service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
                install_components: 'gke-gcloud-auth-plugin'
                export_default_credentials: true

        -
            name: build and push the docker image
            env:
                GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
                IMAGE_NAME: latest-image-10
            run: |
                gcloud auth configure-docker europe-west6-docker.pkg.dev
                docker build -t europe-west6-docker.pkg.dev/amazing-thought-394210/test/$IMAGE_NAME:2.6.5-python3.10 .
                docker push europe-west6-docker.pkg.dev/amazing-thought-394210/test/$IMAGE_NAME:2.6.5-python3.10
